In [274]:
import numpy as np
import math

# Numpy Problems

Problem 1

In [9]:
A = np.array([[3, -1, 4],[1, 5, -9]])
B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9,-3,-2,-3]])

A@B

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2

In [10]:
def poly_mat(A):
    return -(A@A@A) + 9*(A@A) - 15*A

In [11]:
A = np.array([[3, 1, 4],[1, 5, 9], [-5, 3, 1]])
poly_mat(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3

In [38]:
def prob_3():
    A = np.triu(np.ones([7,7]))
    B_1 = np.full_like(A, -1)
    B_1 = np.tril(B_1)
    B_2 = np.full_like(A, 5)
    B_2 = np.triu(B_2)
    B = B_1 + B_2 
    np.fill_diagonal(B, -1)
    res = A@B@A
    return np.int64(res)

In [39]:
prob_3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

Problem 4

In [42]:
def prob_4(A):
    B = np.copy(A)
    mask = A < 0
    B[mask]=0
    return B

In [45]:
prob_4(np.array([-1,-2,-2,1,9,-2,9]))

array([0, 0, 0, 1, 9, 0, 9])

Problem 5

In [60]:
A = np.array([[0,2,4],[1,3,5]])
B = np.tril(np.full([3,3],3))
C = np.diagflat([-1,-1,-1])
Z = np.zeros([3,3])

In [75]:
v1 = np.vstack((Z, A, B))
v2 = np.vstack((A.T, np.zeros([3,2]), np.zeros([2,2])))
v3 = np.vstack((np.eye(3), np.zeros([2,3]), C))
np.hstack((v1,v2,v3))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -1.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -1.]])

Problem 6

In [92]:
def prob_6(A):
    row_sums = A.sum(axis=1)
    new_matrix = A / row_sums[:, numpy.newaxis]
    return new_matrix        

In [93]:
prob_6(np.array([[4,2],[2,1]]))

array([[ 0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333]])

Problem 7

In [97]:
grid = np.load("grid.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'grid.npy'

Problem 7

In [237]:
grid = np.load("grid.npy")
def prob7(g):
    row=np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    col=np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    right = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    left = np.max(grid[3:,:-3]*grid[2:-1,1:-2]*grid[1:-2,2:-1]*grid[:-3,3:])
    res = max(row,col,right,left)
    for k in [-1,-2,-3]:
        mat1 = g[k,g.shape[0]-4:]
        mat2 = g[g.shape[0]-4:,k]
    return res
prob7(grid)

70600674

# Standard Python

Problem 1

In [4]:
def prob_1(L):
    print(min(L), max(L), sum(L)/len(L))

In [5]:
prob_1([1,2,3])

1 3 2.0


Problem 2

In [119]:
a = 1
new = a
new = 2
print(new == a)
b = "a"
new = b
new = "b"
print(new == b)

c = [1,2]
new = c
new[1] = 10
print(new == c)

d = (1,2)
new = d
new = (2,1)
print(new == d)

e = set([1,2])
new = e
new = set([2,2])
print(new == e)


False
False
True
False
False


Problem 3

In [125]:
def my_sum(a,b):
    return a+b
def hyp(a,b):
    return math.sqrt(my_sum(a*a, b*b))

In [126]:
hyp(1,2)

2.23606797749979

Problem 4

In [130]:
def power_set(A):
    l = len(A)
    for i in range(1 << l):
        print([A[j] for j in range(l) if (i & (1 << j))])

In [131]:
power_set([1,2,3])

[]
[1]
[2]
[1, 2]
[3]
[1, 3]
[2, 3]
[1, 2, 3]


# Unit Testing

See corresponding .py file

# Object Oriented

Problem 1

In [175]:
class Backpack:
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        """Set the name and initialize an empty list of contents.
        Parameters:
        name (str): the name of the backpack's owner.
        """
        self.name = name # Initialize some attributes.
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):
        """Add 'item' to the backpack's list of contents."""
        if len(self.contents) > self.max_size:
            print("Overcapacity")
        else:
            self.contents.append(item) # Use 'self.contents', not just 'contents'.
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
    def dump(self): # remove contents
        self.contents = []

In [165]:
def test_backpack(name):
    testpack = Backpack(name, "black") # Instantiate the object.
    if testpack.name != "Barry": # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) # Test a method.
    print("Contents:", testpack.contents)

In [166]:
test_backpack("Barry")

Contents: ['pencil', 'pen', 'paper', 'computer']


In [167]:
test_backpack("no")

Backpack.name assigned incorrectly
Contents: ['pencil', 'pen', 'paper', 'computer']


Problem 2

In [181]:
class Jetpack(Backpack):
    # this is a jetpack which is a backpack but with fuel
    def __init__(self, name, color, max_size=2, fuel=10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    def fly(self, fuel_burned): # bunrs the fuel
        self.fuel = self.fuel - fuel_burned 
    def dump(self): # dumps everything including fuel
        Backpack.dump(self)
        self.fuel = 0

In [182]:
j = Jetpack("Ari", "blue")

In [183]:
j.fly(4)
j.fuel

6

In [184]:
j.dump()

In [185]:
j.fuel

0

Problem 3

In [189]:
class Backpack:
    def __init__(self, name, color, max_size = 5): # This function is the constructor.
        """Set the name and initialize an empty list of contents.
        Parameters:
        name (str): the name of the backpack's owner.
        """
        self.name = name # Initialize some attributes.
        self.contents = []
        self.color = color
        self.max_size = max_size

    def put(self, item):
        """Add 'item' to the backpack's list of contents."""
        if len(self.contents) > self.max_size:
            print("Overcapacity")
        else:
            self.contents.append(item) # Use 'self.contents', not just 'contents'.
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
    def dump(self): # remove contents
        self.contents = []
    def __eq__(self, other): # is it the same
        if (self.name == other.name) & (self.color == other.color) & (len(self.contents) == len(other.contents)):
            return True
    def __str__():
        return '''Owner:\t\t{}
        \nColor:\t\t{} 
        \nSize:\t\t{}
        \nMax Size:\t{}
        \nContents:\t{}'''.format(self.name,self.color,len(self.contents),
                                  self.max_size, self.contents)

Problem 4

In [231]:
class ComplexNumber:
    def __init__(self, a ,b):
        self.real = a
        self.imag = b
    
    def conjugate(self):
        b = -self.imag
        return ComplexNumber(self.real, b)
    def __str__(self):
        return("("+str(self.real) + "" + str(self.imag) + "j)")
    def __abs__(self):
        return math.sqrt(self.real ** 2 + self.imag ** 2)
    def __eq__(self, other):
        return (self.real == other.real) and (self.imag == other.imag)
    def __add__(self, other):
        real = self.real + other.real
        imag = self.imag + other.imag
        return ComplexNumber(real, imag)

    def __sub__(self, other):
        real = self.real - other.real
        imag = self.imag - other.imag
        return ComplexNumber(real, imag)

    def __mul__(self, other):
        real = self.real*other.real - self.imag*other.imag
        imag = self.imag*other.real + other.imag*self.real
        return ComplexNumber(real, imag)
        
    def __truediv__(self, other):
            t = self*other.conjugate()
            b = (other*other.conjugate()).real
            res = ComplexNumber(t.real / b, t.imag/b)
            return res

In [249]:
def test_ComplexNumber(a, b):
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
        if str(py_cnum) != str(my_cnum):
            print("__str__() failed for", py_cnum)
    print(my_cnum-my_cnum)
    print(my_cnum*my_cnum)
    print(my_cnum-my_cnum)
    print(abs(my_cnum))
    print(my_cnum==py_cnum)




In [250]:
test_ComplexNumber(4,-6)

(00j)
(-20-48j)
(00j)
7.211102550927978
True


# I/O

Problem 1

In [1]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                           "digits differ by 2 or more: ")
    if len(step_1) != 3:
        raise ValueError("The first number is not a 3-digit number.")
    if abs(int(step_1[2])-int(step_1[0])) < 2:
        raise ValueError("The first number’s first and last digits differ by less than 2.")
    step_2 = input("Enter the reverse of the first number, obtained "
                                              "by reading it backwards: ")
    if int(step_2[2]) != int(step_1[0]) or int(step_2[0]) != int(step_1[2]) or int(step_2[1]) != int(step_1[1]):
        raise ValueError("The second number is not the reverse of the first number.")
    step_3 = input("Enter the positive difference of these numbers: ")
    if int(step_3) != abs(int(step_1)-int(step_2)):
        raise ValueError("The third number is not the positive difference of the first two numbers.")
    step_4 = input("Enter the reverse of the previous result: ")
    if int(step_4[2]) != int(step_3[0]) or int(step_4[0]) != int(step_3[2]) or int(step_4[1]) != int(step_3[1]):
        raise ValueError("The fourth number is not the reverse of the third number.")
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [4]:
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 123
Enter the reverse of the first number, obtained by reading it backwards: 321
Enter the positive difference of these numbers: 198
Enter the reverse of the previous result: 891
198 + 891 = 1089 (ta-da!)


Probem 2

In [5]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    try:
        for i in range(int(max_iters)):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Interrupted at ", i)
    else:
        print("completed")
    finally:
        return(walk)

In [6]:
random_walk()

Interrupted at  14947202


3140

Problem 3

In [1]:
class ContentFilter(object):
    def __init__(self, filename):
        self.file = filename
        try:
            with open(self.file,"r") as myfile:
                self.content = myfile.read().split('\n')
        except FileNotFoundError:
            file = input("Please enter a valid file name:")
            ContentFilter(file)
        except TypeError:
            file = input("Please enter a valid file name:")
            ContentFilter(file)
        except OSError:
            file = str(input("Please enter a valid file name:"))
            ContentFilter(file)

In [2]:
cf1 = ContentFilter("helloworld.txt")

Please enter a valid file name:hdjhw
Please enter a valid file name:grid.npy


Problem 4

In [55]:
class ContentFilter(object):
    def __init__(self, filename):
        self.file = filename
        try:
            with open(self.file,"r") as myfile:
                self.content = myfile.read().split('\n')
        except FileNotFoundError:
            file = input("Please enter a valid file name:")
            ContentFilter(file)
        except TypeError:
            file = input("Please enter a valid file name:")
            ContentFilter(file)
        except OSError:
            file = str(input("Please enter a valid file name:"))
            ContentFilter(file)
        self.tot = 0
        self.alpha = 0
        self.num = 0
        self.white = 0
        self.lines = len(self.content)
        for i in range(self.lines):
            for j in range(len(self.content[i])):
                self.tot += 1
                if self.content[i][j].isspace():
                    self.white += 1
                if self.content[i][j].isdigit():
                    self.num += 1
                if self.content[i][j].isalpha():
                    self.alpha += 1
    def uniform(self, new_file, case="upper"):
        if case not in ['upper','lower']:
            raise ValueError("Case should be 'upper' or 'lower'")
        with open(new_file, "w") as new_file:
            for i in range(len(self.content)):
                if case == "upper":
                    new_file.write(self.content[i].upper() + "\n")
                elif case == "lower":
                    new_file.write(self.content[i].lower() + "\n")
                    
    def reverse(self, new_file, unit ="line"):
        if unit not in ['line','word']:
            raise ValueError("Case should be'line' or 'unit'")
        with open(new_file, "w") as file:
                if unit == "word":
                    for i in range(len(self.content)):
                        file.write(self.content[i][::-1] + "\n")
                else:
                    for i in range(len(self.content)):
                        file.write(self.content[::-1][i] + "\n")
                        
    def transpose(self, new_file):
        with open(new_file, "w") as file:
            for i in range(len(self.content[0].split())):
                new_line = []
                for j in range(len(self.content)):
                    c = self.content[j].split()
                    new_line.append(c[i])
                file.write(" ".join(new_line) + "\n")
                
    def __str__(self):
        return "File: {}".format(self.file) + "\n" + "Total chars: {}".format(self.tot) + "\n" + "Alphabetic chars: {}".format(self.alpha) \
                + "\n" + "Numerical: {}".format(self.num) + "\n" + "Whitespace: {}".format(self.white) + "\n" + "# lines: {}".format(self.lines)

In [56]:
cf = ContentFilter("cf_example1.txt")
cf.uniform("uniform.txt", case="upper")
cf.uniform("uniform.txt", case="lower")
cf.reverse("reverse.txt", unit="word")
cf.reverse("reverse.txt",unit="line")
cf.transpose("transpose.txt")

In [57]:
print(cf)

File: cf_example1.txt
Total chars: 10
Alphabetic chars: 6
Numerical: 0
Whitespace: 4
# lines: 2
