## Problem Set 3
### Ari Boyarsky

### QR Decomposition

In [3]:
import numpy as np
from scipy import linalg as la 

#### Problem 1

In [4]:
def qr(A):
    m,n = A.shape
    Q = np.copy(A)
    R = np.zeros((n,n))
    for i in range(n):
        R[i,i] = la.norm(Q[:,i])
        Q[:,i] = Q[:,i]/R[i,i]
        for j in range(i+1, n):
            R[i,j] = Q[:,j].transpose() @ Q[:,i]
            Q[:,j] = Q[:,j] - (R[i,j]*Q[:,i])
    
    return(Q,R)
        

In [5]:
A = np.random.random((6,4))

In [6]:
Q,R = qr(A)

In [7]:
Q@R

array([[ 0.15307668,  0.71740954,  0.65120962,  0.63028468],
       [ 0.37670137,  0.69307387,  0.40977603,  0.33798711],
       [ 0.54262376,  0.92509258,  0.1743104 ,  0.44505761],
       [ 0.90629343,  0.83844638,  0.15427493,  0.1931124 ],
       [ 0.63909417,  0.36904527,  0.75922454,  0.22504297],
       [ 0.88764516,  0.99375127,  0.72304957,  0.79080557]])

In [8]:
Q,R = la.qr(A, mode="economic")

In [9]:
Q

array([[-0.09725282, -0.69330787,  0.43408153, -0.0675811 ],
       [-0.23932627, -0.34805362,  0.07176364, -0.47164294],
       [-0.34474024, -0.40858755, -0.39858875, -0.01570005],
       [-0.57578719,  0.21249328, -0.48028989, -0.27920625],
       [-0.40602991,  0.43125089,  0.61920739, -0.34832116],
       [-0.56393956, -0.01040994,  0.18290444,  0.75726844]])

In [10]:
R

array([[-1.57400763, -1.74758326, -1.0263476 , -0.94414778],
       [ 0.        , -0.78962343, -0.31266211, -0.60661114],
       [ 0.        ,  0.        ,  0.77087666,  0.31169536],
       [ 0.        ,  0.        ,  0.        ,  0.25755469]])

In [11]:
A

array([[ 0.15307668,  0.71740954,  0.65120962,  0.63028468],
       [ 0.37670137,  0.69307387,  0.40977603,  0.33798711],
       [ 0.54262376,  0.92509258,  0.1743104 ,  0.44505761],
       [ 0.90629343,  0.83844638,  0.15427493,  0.1931124 ],
       [ 0.63909417,  0.36904527,  0.75922454,  0.22504297],
       [ 0.88764516,  0.99375127,  0.72304957,  0.79080557]])

#### Problem 2

In [12]:
A = np.random.random((4,4))
def get_det(A):
    m,n = A.shape
    if m != n:
        raise Exception("Error, A must be invertible!")
    Q,R = qr(A)
    return R.diagonal().prod() # one line ;)

In [13]:
np.abs(get_det(A))

0.00066702389754351422

In [14]:
np.abs(la.det(A))

0.00066702389754353655

#### Problem 3

In [15]:
A = np.random.random((4,4))
b = np.random.random(4)
Q,R = qr(A)

y = Q.transpose() @ b

def backwds_sub(R, y):
    m,n = R.shape
    if m != n:
        raise Exception("Error, A must be invertible!")
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        s = R[i,i]
        for j in range(n-1,i-1,-1):
            if i == j:
                s = np.dot(R[j,:],x)
                x[i] = (y[i]-s)/R[j,i]
    print(x)

In [16]:
backwds_sub(R,y)

[ 0.21151455  2.26156966  0.21876045 -1.41610958]


In [17]:
la.solve(R,y)

array([ 0.21151455,  2.26156966,  0.21876045, -1.41610958])

#### Problem 4

In [51]:
def householder(A):
    m,n = A.shape
    R = np.copy(A)
    Q = np.eye(m)
    for k in range(n-1):
        u = np.copy(R[k:,k])
        u[0] = u[0] + np.sign(u[0])*la.norm(u)
        u = u/la.norm(u)
        R[k:,k:] = R[k:,k:] - 2 * np.outer(u, (u.T @ R[k:,k:]))
        Q[k:,:] = Q[k:,:] - 2*np.outer(u, (u.T @ Q[k:,:]))
    return(Q.T, R)

In [52]:
A = np.random.random((4,5))
householder(A)

(array([[-0.63432671, -0.08038772,  0.68430504, -0.35056249],
        [-0.04253993, -0.97659197, -0.19510987, -0.07994139],
        [-0.67564011,  0.02781164, -0.27235858,  0.68451279],
        [-0.3732699 ,  0.19756634, -0.64767242, -0.63415894]]),
 array([[ -1.13102098e+00,  -1.40092664e+00,  -1.02856593e+00,
          -5.51297094e-01,  -4.61708542e-01],
        [ -6.93889390e-18,  -5.86271726e-01,  -5.92034190e-01,
          -8.64731229e-01,   4.78640958e-02],
        [ -1.11022302e-16,   0.00000000e+00,  -4.32801047e-01,
          -1.70227496e-01,  -4.80227807e-01],
        [ -1.11022302e-16,   0.00000000e+00,   5.55111512e-17,
           1.37967708e-01,  -3.66610930e-01]]))

In [49]:
la.qr(A, mode="economic")

(array([[-0.59463297,  0.52017609, -0.6029092 ,  0.11103586],
        [-0.74721324, -0.07653575,  0.65272915, -0.09878926],
        [-0.22368542, -0.61166004, -0.42312236, -0.62992405],
        [-0.19506112, -0.59112699, -0.17723608,  0.76230402]]),
 array([[-1.21941882, -1.08786695, -0.95665812, -1.07320105, -0.47166618],
        [ 0.        , -1.23117189,  0.03595586, -0.38328077, -0.30879726],
        [ 0.        ,  0.        , -0.39806367, -0.62431332, -0.09776254],
        [ 0.        ,  0.        ,  0.        ,  0.3550416 ,  0.34972064]]))

#### Problem 5

In [70]:
def hessenberg(A):
    m,n = A.shape
    if m != n:
        raise Exception("Error, A must be n x n!")
    H = np.copy(A)
    Q = np.eye(m)
    for k in range(n-3):
        u = np.copy(H[k+1:, k])
        u[0] = u[0] + np.sign(u[0])*la.norm(u)
        u = u/la.norm(u)
        H[1+k:,k:] = H[k+1:, k:] - 2*np.outer(u, (u.T @ H[k+1:, k:]))
        H[:,k+1:] = H[:, k+1:] - 2*np.outer(H[:, k+1:] @ u, u.T)
        Q[1+k:,k:] = Q[k+1:, k:] - 2*np.outer(u, (u.T @ Q[k+1:, k:]))
    return(H, Q.T)

In [73]:
A = np.random.random((4,4))
hessenberg(A)

(array([[  8.02129917e-01,  -8.01113629e-01,   5.89340173e-01,
          -3.68135168e-04],
        [ -1.14598295e+00,   1.19411816e+00,  -6.77587328e-01,
          -6.91800445e-01],
        [  0.00000000e+00,  -2.21884079e-01,  -1.90038398e-01,
           4.97769444e-01],
        [  0.00000000e+00,  -4.57974362e-01,  -1.20310247e-01,
          -2.91877123e-01]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.80123683, -0.31071335, -0.51134797],
        [ 0.        , -0.31071335,  0.94640195, -0.08820753],
        [ 0.        , -0.51134797, -0.08820753,  0.85483489]]))